#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  9 02:35:19 2020

@author: Thisal
"""


from sklearn import tree

features = [[140, 1], [130, 1], [150, 0],[170, 0]]
labels = ["apple", "apple", "orange", "orange"]

clf = tree.DecisionTreeClassifier()

clf = clf.fit(features, labels)

print (clf.predict([[145, 0]]))

print("Hello Thisal")
 